nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.3.1.cjs

npmRegistries:
  //tfs.omnibees.com/tfs/IDTProjects/Omnibees/_packaging/bee2pay/npm/registry/:
    npmAlwaysAuth: true
    npmAuthIdent: "${NPM_AUTH_TOKEN}"
 
npmScopes:
  bee2pay:
    npmAlwaysAuth: true
    npmRegistryServer: "${NPM_REGISTRY}"
